applications:
  zapier:
    component: zapierWebHookIntegration
    name: Zapier
    description: "Add an ecosystem of 600+ apps to the Symphony platform. Zapier sends notifications and content to Symphony IMs or rooms from your favorite applications including GMail, Office 365, Trello, HubSpot, Twitter, LinkedIn, and hundreds of other productivity apps."
    publisher: Symphony
    context: zapier
    keystore:
      password: ${KEYSTORE_PASS}
